menu:
  首页: /
  项目: /项目/
  职业生涯: /职业生涯/
  随感: /随感/
  归档: /archives
  关于我: /about

widgets:
- search
- category
- recent_posts
- tagcloud

duoshuo_shortname: longling

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  weibo: true
  linkedin: true
  google: false
  facebook: false
  twitter: false
  pinterest: false

highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

copyright:
  enable: true
  claim: 版权声明：自由转载-非商用-无演绎-保持署名 @ Creative Commons BY-NC-ND 3.0
  show_link: true

fancybox: true

google_analytics: UA-45019001-1
analytics_site_name: topdna.org
rss:

comment_provider: facebook
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
